services:
  mysql:
    image: mysql:8.0
    container_name: minidoodle-database-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minidoodle
    ports:
      - "3307:3306"
    volumes:
      - minidoodle_mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: minidoodle-backend-container
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/minidoodle
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  minidoodle_mysql_data: